### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sFxMTA** [MichaelBelgium/Youtube-API#34]
Hello, i installed and added to environment paths ffmpeg and yt-dlp but for some reasons this part of the code `$dl->setBinPath($ytdlp);` breaks my php page showing a HTTP ERROR 500, without it says `{"error":true,"message":"\"youtube-dl\" executable was not found. Did you forgot to configure it's binary path? ex.: $yt->setBinPath('\/usr\/bin\/youtube-dl') ?."}`
I tried to configure it in my own way with `$dl->setBinPath("C:\inetpub\wwwroot\yt_api\yt-dlp.exe");` but still doesn't works.
Yeah if you wonder i'm using **windows**, not linux

**Comment by MichaelBelgium** [comment]
Never tested it on Windows so mhm

Did you try
```
$dl->setBinPath("C:\inetpub\wwwroot\yt_api");
```
or 
```
$dl->setBinPath("C:\\inetpub\\wwwroot\\yt_api\\yt-dlp.exe");
```

Like only the folder or double quotes (not sure if that'll work)

**Comment by sFxMTA** [comment]
> Never tested it on Windows so mhm
> 
> Did you try
> 
> ```
> $dl->setBinPath("C:\inetpub\wwwroot\yt_api");
> ```
> 
> or
> 
> ```
> $dl->setBinPath("C:\\inetpub\\wwwroot\\yt_api\\yt-dlp.exe");
> ```
> 
> Like only the folder or double quotes (not sure if that'll work)

Yes i tried tho the bin path is already set on environment variables aswell, but when i use setBinPath i get a error 500...
I'm actually sticking with yt-dlp without any kind of php api but this is nasty, it would be way better with your api, also some commands with exec won't work due to permissions so yeah, i'd def stick with your api if i found a way to make it work, i was using it in the past with a linux vps and i loved it but now i'm on a windows vps and i can't switch

**Comment by MichaelBelgium** [comment]
Do you have yt-dlp folder added in PATH (, so you also can use it in CLI from anywhere) ?
If you have it in PATH, I don't think you need `$dl->setBinPath`

EDIT: you could also try forward slashes 
```
$dl->setBinPath("C:/inetpub/wwwroot/yt_api/yt-dlp.exe");
```

**Comment by sFxMTA** [comment]
> Do you have yt-dlp folder added in PATH (, so you also can use it in CLI from anywhere) ? If you have it in PATH, I don't think you need `$dl->setBinPath`
> 
> EDIT: you could also try forward slashes
> 
> ```
> $dl->setBinPath("C:/inetpub/wwwroot/yt_api/yt-dlp.exe");
> ```

I got it in my environment variables, i could use it from any directory by just typing "yt-dlp link" in cmd along with ffmpeg

If i get rid of setBinPath the problem seems to be on getVideos

**Comment by MichaelBelgium** [comment]
> If i get rid of setBinPath the problem seems to be on getVideos

What problem? I think that's progress, and that you don't ned setBinPath

**Comment by dennorske** [comment]
I recommend that you look into running docker on your Windows host, and deploy using that, if possible :)

**Comment by sFxMTA** [comment]
> > If i get rid of setBinPath the problem seems to be on getVideos
> 
> What problem? I think that's progress, and that you don't ned setBinPath

Notice: Undefined offset: 0 in C:\inetpub\wwwroot\yt_api\mic\convert.php on line 103

Fatal error: Uncaught Error: Call to a member function getError() on null in C:\inetpub\wwwroot\yt_api\mic\convert.php:105
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\yt_api\mic\convert.php on line 105

If i freeze getError the problem appears to be getVideos, so i guess the functions can't load properly for some reasons, i installed it through composer so i'm sure there's everything included



> I recommend that you look into running docker on your Windows host, and deploy using that, if possible :)

Yeah i might eventually try it tho it would be my first time using docker

**Comment by MichaelBelgium** [comment]
That looks like it did not find any video's? What video are you trying to convert

**Comment by sFxMTA** [comment]
I tried with many different videos but everything gives the same, also not sure it's about the video since it cannot even reach getError

**Comment by sFxMTA** [comment]
Yes, whenever i set the bin path the page returns a 500 error :(

________________________________
